Controllers/EconomicController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using AccountedOfFamily.Models.Repositories;
using AccountedOfFamily.Models.ViewModels;
using AccountedOfFamily.Infrastructure;
using AccountedOfFamily.Models.Identity;
using Microsoft.AspNetCore.Authorization;

namespace AccountedOfFamily.Controllers
{
    [Authorize]
    public class EconomicController : Controller
    {
        private IDepositRepository depositRepository;
        private IECategoryRepository eCategoryRepository;
        private IExpenseRepository expenseRepository;
        private IInCategoryRepository inCategoryRepository;
        private IIncomeRepository incomeRepository;
        private IWaitingTransactionRepository waitingTransactionRepository;

        public EconomicController(IDepositRepository depRepo, IECategoryRepository eCatRepo,
            IExpenseRepository expenseRepo, IInCategoryRepository inCatRepo, IIncomeRepository incomeRepo,
            IWaitingTransactionRepository WaitRepo)
        {
            depositRepository = depRepo;
            eCategoryRepository = eCatRepo;
            expenseRepository = expenseRepo;
            inCategoryRepository = inCatRepo;
            incomeRepository = incomeRepo;
            waitingTransactionRepository = WaitRepo;
        }

        public IActionResult Deposits() =>
            View(new DepositsViewModel { Deposits = depositRepository.Deposits });


        public IActionResult ECategories() =>
            View(new ECategoriesViewModel { ECategories = eCategoryRepository.ECategories });


        public IActionResult Expenses(int year = 1, int month = 0)
        {
            if (year == 1)
            {
                year = expenseRepository.MaxDate.Year;
            }
            if (month==0)
            {
                month = expenseRepository.MaxDate.Month;
            }
            if (month > 12 || month < 1 || year < 1900 || year > 2100) return Forbid();
            var expenses = expenseRepository
                .InInterval(new DateTime(year, month, 1), new DateTime(year, month, LastDay(month, year),23,59,59));

            return View(new PagedModel<Expense>
            {
                Year = year,
                Month = month,
                MaxDate = expenseRepository.MaxDate,
                MinDate = expenseRepository.MinDate,
                Months = expenseRepository.Months,
                Elements = expenses
            });
        }

        public IActionResult InCategories() =>
            View(new InCategoriesViewModel { InCategories = inCategoryRepository.InCategories });


        public IActionResult Incomes(int year = 1, int month = 0)
        {
            if (year == 1)
            {
                year = expenseRepository.MaxDate.Year;
            }
            if (month == 0)
            {
                month = expenseRepository.MaxDate.Month;
            }
            if (month > 12 || month < 1 || year < 1900 || year > 2100) return Forbid();
            var incomes = incomeRepository
                .InInterval(new DateTime(year, month, 1), new DateTime(year, month, LastDay(month, year),23,59,59));
            return View(new PagedModel<Income>
            {
                Year = year,
                Month = month,
                MaxDate = incomeRepository.MaxDate,
                MinDate = incomeRepository.MinDate,
                Months = incomeRepository.Months,
                Elements = incomes
            });
        }
        public IActionResult WaitingTransactions(int year = 1, int month = 0)
        {
            if (year == 1)
            {
                year = expenseRepository.MaxDate.Year;
            }
            if (month == 0)
            {
                month = expenseRepository.MaxDate.Month;
            }
            if (month > 12 || month < 1 || year < 1900 || year > 2100) return Forbid();
            var incomes = waitingTransactionRepository
                .EndInInterval(new DateTime(year, month, 1), new DateTime(year, month, LastDay(month, year),23,59,59));

            return View(new PagedModel<WaitingTransaction>
            {
                Year = year,
                Month = month,
                MaxDate = waitingTransactionRepository.MaxDate,
                MinDate = waitingTransactionRepository.MinDate,
                Months = waitingTransactionRepository.Months,
                Elements = incomes.OrderByDescending(e => e.EndDate)
            });
        }

        public static int LastDay(int month, int year)
        {
            switch (month)
            {
                case 1: return 31;
                case 2: if (year % 4 == 0) return 29; else return 28;
                case 3: return 31;
                case 4: return 30;
                case 5: return 31;
                case 6: return 30;
                case 7: return 31;
                case 8: return 31;
                case 9: return 30;
                case 10: return 31;
                case 11: return 30;
                case 12: return 31;
                default: return 31;


            }
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AccountedOfFamily</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" asp-href-include="~/lib/fontawesome-free-6.1.1-web/css/*.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" href="/">
                    <img src="~/images/logo.png" class="logo" />
                </a>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a href="/" class="nav-link text-dark">Главная</a>
                        </li>
                        <li class="nav-item">
                            <a asp-action="Incomes" asp-controller="Economic"
                               class="nav-link text-dark">Доходи</a>
                        </li>
                        <li class="nav-item">
                            <a asp-action="Expenses" asp-controller="Economic"
                               class="nav-link text-dark">Затраты</a>
                        </li>
                        <li class="nav-item">
                            <a asp-action="Deposits" asp-controller="Economic"
                               class="nav-link text-dark">Депозити</a>
                        </li>
                        <li class="nav-item">
                            <a asp-action="WaitingTransactions" asp-controller="Economic"
                               class="nav-link text-dark">Планирование</a>
                        </li>
                        @await Component.InvokeAsync("AdminPanel")
                    </ul>
                </div>
            </div>
        </nav>
        
    </header>
    <div class="container">
        @RenderBody()
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - AccountedOfFamily
        </div>
    </footer>



    <script>
        $(document).ready(function () {
            $('.custom-file-input').on("change", function () {
                var fileName = $(this).val().split("\\").pop();
                console.log("fayl tanlandi");
                $(this).next('.custom-file-label').html(fileName);
            })
        })
    </script>

</body>
</html>