Models/ViewModels/DepositsViewModel.cs
using System;
using System.Collections.Generic;
using AccountedOfFamily.Models.Identity;

namespace AccountedOfFamily.Models.ViewModels
{
    public class DepositsViewModel
    {
        public IEnumerable<Deposit> Deposits { get; set; }

    }
}

Models/ViewModels/IncomesViewModel.cs
using System;
using System.Collections.Generic;using AccountedOfFamily.Models.Identity;

namespace AccountedOfFamily.Models.ViewModels
{
    public class IncomesViewModel
    {
        public IEnumerable<Income> Incomes { get; set; }
    }
}

Controllers/DepositsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using AccountedOfFamily.Models.Identity;
using AccountedOfFamily.Models.Repositories;
using AccountedOfFamily.Models.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace AccountedOfFamily.Controllers
{
    [Authorize]
    public class DepositsController : Controller
    {
        UserManager<AppUser> userManager;
        IDepositRepository depositRepository;
        public DepositsController(IDepositRepository depRepo,UserManager<AppUser> useMng)
        {
            depositRepository = depRepo;
            userManager = useMng;
        }
        [HttpPost]
        public IActionResult Delete(long id,string returnUrl)
        {
            depositRepository.Delete(id);
            return Redirect(returnUrl);
        }

        public IActionResult Edit(long id, string returnUrl)
        {
            Deposit deposit = depositRepository.GetOne(id);
            if (deposit == null) return Redirect(returnUrl);
            ViewBag.returnUrl = returnUrl;
            DepositEditModel editingDeposit = new DepositEditModel
            {
                Deposit = deposit
            };
            editingDeposit.Users = new Dictionary<string, string>();
            foreach (var user in userManager.Users)
            {
                editingDeposit.Users.Add(user.Id, user.FirstName);
            }
            return View(editingDeposit);
        }

        [HttpPost]
        public IActionResult Update(Deposit deposit,string returnUrl)
        {
            depositRepository.Update(deposit);
            return Redirect(returnUrl);
        }

        public IActionResult Create(string returnUrl)
        {
            ViewBag.returnUrl = returnUrl;
            return View(new DepositEditModel
                {
                    Deposit = new Deposit(),
                    Users = userManager.Users.ToDictionary(u => u.Id, u => u.FirstName)
                });
        }

        [HttpPost]
        public IActionResult Create(Deposit deposit, string returnUrl)
        {
            deposit.Id = 0;
            deposit.DateStart = DateTime.Now;
            depositRepository.Add(deposit);
            return Redirect(returnUrl);
        }

    }
}

Controllers/ECategoryController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AccountedOfFamily.Models.Identity;
using AccountedOfFamily.Models.Repositories;
using AccountedOfFamily.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;

namespace AccountedOfFamily.Controllers
{
    [Authorize]
    public class ECategoryController : Controller
    {
        private IECategoryRepository eCategoryRepository;
        public ECategoryController(IECategoryRepository repo)
        {
            eCategoryRepository = repo;
        }

        [HttpPost]
        public IActionResult Delete(long id, string returnUrl)
        {
            eCategoryRepository.Delete(id);
            return Redirect(returnUrl);
        }

        public IActionResult Edit(long id,string returnUrl)
        {
            ViewBag.returnUrl = returnUrl;
            return View(new ECategoryEditModel { ECategory = eCategoryRepository.Get(id) });
        }

        [HttpPost]
        public IActionResult Update(ECategory category,string returnUrl)
        {
            eCategoryRepository.Update(category);
            return Redirect(returnUrl);
        }

        public IActionResult Create(string returnUrl)
        {
            ViewBag.returnUrl = returnUrl;
            return View(new ECategoryEditModel { ECategory = new ECategory() });
        }

        [HttpPost]
        public IActionResult Create(ECategory category, string returnUrl)
        {
            eCategoryRepository.Add(category);
            return Redirect(returnUrl);
        }
    }
}

Controllers/ExpenseController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AccountedOfFamily.Models.Identity;
using AccountedOfFamily.Models.Repositories;
using AccountedOfFamily.Models.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace AccountedOfFamily.Controllers
{
    [Authorize]
    public class ExpenseController : Controller
    {
        private IExpenseRepository expenseRepository;
        private IECategoryRepository eCategoryRepository;
        private UserManager<AppUser> userManager;
        public ExpenseController(IExpenseRepository repo, IECategoryRepository erepo, UserManager<AppUser> userMng)
        {
            expenseRepository = repo;
            eCategoryRepository = erepo;
            userManager = userMng;
        }

        [HttpPost]
        public IActionResult Delete(long id, string returnUrl)
        {
            expenseRepository.Delete(id);
            return Redirect(returnUrl);
        }

        public IActionResult Edit(long id, string returnUrl)
        {
            Expense expense = expenseRepository.Get(id);
            ViewBag.returnUrl = returnUrl;
            return View(new ExpenseEditModel
            {
                Expense = expense,
                Users = userManager.Users.ToDictionary(u => u.Id, u => u.FirstName),
                Categories = eCategoryRepository.ECategories.ToList()
            });
        }
        [HttpPost]
        public IActionResult Update(Expense expense,string returnUrl, string NewCategoryName, string NewCategoryDescription)
        {
            if (expense.ECategoryId==-1)
            {
                expense.ECategoryId = 0;
                expense.ECategory = new ECategory { Id = 0, Name = NewCategoryName, Description = NewCategoryDescription };
            }
            expenseRepository.Update(expense);
            return Redirect(returnUrl);
        }

        public IActionResult Create(string returnUrl)
        {
            ViewBag.returnUrl = returnUrl;
            return View(new ExpenseEditModel
            {
                Expense = new Expense(),
                Users = userManager.Users.ToDictionary(u => u.Id, u => u.FirstName),
                Categories=eCategoryRepository.ECategories.ToList()
            });
        }

        [HttpPost]
        public IActionResult Create(Expense expense,string returnUrl, string NewCategoryName, string NewCategoryDescription)
        {
            expense.Id = 0;
            expense.DateExpense = DateTime.Now;
            if (expense.ECategoryId == -1)
            {
                expense.ECategoryId = 0;
                expense.ECategory = new ECategory { Id = 0, Name = NewCategoryName, Description = NewCategoryDescription };
            }

            expenseRepository.Add(expense);
            return Redirect(returnUrl);
        }
    }
}

Controllers/InCategoryController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AccountedOfFamily.Models.ViewModels;
using AccountedOfFamily.Models.Repositories;
using AccountedOfFamily.Models.Identity;
using Microsoft.AspNetCore.Authorization;

namespace AccountedOfFamily.Controllers
{
    [Authorize]
    public class InCategoryController : Controller
    {
        private IInCategoryRepository inCategoryRepository;
        public InCategoryController(IInCategoryRepository repo)
        {
            inCategoryRepository = repo;
        }

        [HttpPost]
        public IActionResult Delete(long id, string returnUrl)
        {
            inCategoryRepository.Delete(id);
            return Redirect(returnUrl);
        }
        
        public IActionResult Edit(long id, string returnUrl)
        {
            ViewBag.returnUrl = returnUrl;
            return View(new InCategoryEditModel
            {
                InCategory = inCategoryRepository.Get(id)
            });
        }

        [HttpPost]
        public IActionResult Update(InCategory inCategory, string returnUrl)
        {
            inCategoryRepository.Update(inCategory);
            return Redirect(returnUrl);
        }

        public IActionResult Create(string returnUrl)
        {
            ViewBag.returnUrl = returnUrl;
            return View(new InCategoryEditModel { InCategory = new InCategory() });
        }

        [HttpPost]
        public IActionResult Create(InCategory inCategory, string returnUrl)
        {
            inCategory.Id = 0;
            inCategoryRepository.Add(inCategory);
            return Redirect(returnUrl);
        }
    }
}

Controllers/IncomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AccountedOfFamily.Models.Identity;
using AccountedOfFamily.Models.Repositories;
using AccountedOfFamily.Models.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace AccountedOfFamily.Controllers
{
    [Authorize]
    public class IncomeController : Controller
    {
        private IIncomeRepository incomeRepository;
        private IInCategoryRepository inCategoryRepository;
        private UserManager<AppUser> userManager;
        public IncomeController(IIncomeRepository incomeRepo, IInCategoryRepository catRepo, UserManager<AppUser> userMng)
        {
            incomeRepository = incomeRepo;
            inCategoryRepository = catRepo;
            userManager = userMng;
        }

        [HttpPost]
        public IActionResult Delete(long id, string returnUrl)
        {
            incomeRepository.Delete(id);
            return Redirect(returnUrl);
        }

        public IActionResult Edit(long id, string returnUrl)
        {
            ViewBag.returnUrl = returnUrl;
            return View(new IncomeEditModel
            {
                Income = incomeRepository.Get(id),
                Users = userManager.Users.ToDictionary(u => u.Id, u => u.FirstName),
                Categories = inCategoryRepository.InCategories.ToList()
            });
        }

        [HttpPost]
        public IActionResult Update(Income income, string returnUrl, string NewCategoryName, string NewCategoryDescription)
        {
            if (income.InCategoryId==-1)
            {
                income.InCategoryId = 0;
                income.InCategory = new InCategory { Name = NewCategoryName, Description = NewCategoryDescription };
            }
            incomeRepository.Update(income);
            return Redirect(returnUrl);
        }

        public IActionResult Create(string returnUrl)
        {
            ViewBag.returnUrl = returnUrl;
            return View(new IncomeEditModel
            {
                Income = new Income(),
                Users = userManager.Users.ToDictionary(u => u.Id, u => u.FirstName),
                Categories = inCategoryRepository.InCategories.ToList()
            });
        }
        
        [HttpPost]
        public IActionResult Create(Income income,string returnUrl, string NewCategoryName, string NewCategoryDescription)
        {
            income.Id = 0;
            income.DateSalary = DateTime.Now;
            if (income.InCategoryId == -1)
            {
                income.InCategoryId = 0;
                income.InCategory = new InCategory { Name = NewCategoryName, Description = NewCategoryDescription };
            }
            incomeRepository.Add(income);
            return Redirect(returnUrl);
        }
    }
}

Controllers/WaitingTransactionController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AccountedOfFamily.Models.Identity;
using AccountedOfFamily.Models.Repositories;
using AccountedOfFamily.Models.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace AccountedOfFamily.Controllers
{
    [Authorize]
    public class WaitingTransactionController : Controller
    {
        public IWaitingTransactionRepository repository;
        public UserManager<AppUser> userManager;
        public WaitingTransactionController(IWaitingTransactionRepository repo, UserManager<AppUser> userMng)
        {
            repository = repo;
            userManager = userMng;
        }

        [HttpPost]
        public IActionResult Delete(long id, string returnUrl)
        {
            repository.Delete(id);
            return Redirect(returnUrl);
        }

        public IActionResult Edit(long id, string returnUrl)
        {
            ViewBag.returnUrl = returnUrl;
            return View(new WaitingTransactionEditModel
            {
                WaitingTransaction = repository.Get(id),
                Users = userManager.Users.ToDictionary(u => u.Id, u => u.FirstName)
            });
        }

        [HttpPost]
        public IActionResult Update(WaitingTransaction transaction, string returnUrl)
        {
            repository.Update(transaction);
            return Redirect(returnUrl);
        }

        public IActionResult Create(string returnUrl)
        {
            ViewBag.returnUrl = returnUrl;
            return View(new WaitingTransactionEditModel
            {
                WaitingTransaction = new WaitingTransaction { EndDate=DateTime.Now },
                Users = userManager.Users.ToDictionary(u => u.Id, u => u.FirstName)
            });
        }

        [HttpPost]
        public IActionResult Create(WaitingTransaction transaction, string returnUrl)
        {
            transaction.StartDate = DateTime.Now;
            repository.Add(transaction);
            return Redirect(returnUrl);
        }

    }
}

Views/Economic/Deposits.cshtml
@model DepositsViewModel

<h4 class="bg-primary p-2">Депозити</h4>

<a class="btn btn-primary" asp-action="Create" asp-controller="Deposits"
   asp-route-returnUrl="@Context.Request.PathAndQuery()">Добавить</a>
<table class="table table-striped table-sm table-bordered">
    <thead>
        <tr>
            <th>Номер счёта</th>
            <th>Сумма</th>
            <th>Депозитор(Банк)</th>
            <th>Время вложения денег</th>
            <th>Срок</th>
            <th>Владелец</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <tr class="place"><td colspan="7" class="text-center"> No Data </td></tr>
        @foreach (var d in Model.Deposits)
        {
            <tr>
                <td>@d.NumberAccountDeposit</td>
                <td>@d.Amount</td>
                <td>@d.Depositor</td>
                <td>@d.DateStart</td>
                <td>@d.Deadline</td>
                <td>@d.AppUser.FirstName</td>
                <td>
                    <form method="post" asp-action="Delete" asp-controller="Deposits">                        
                        <input name="Id" value="@d.Id" type="hidden" />
                        <input type="hidden" name="returnUrl" value="@Context.Request.PathAndQuery()" />
                        <a asp-action="Edit" asp-controller="Deposits" asp-route-id="@d.Id" asp-route-returnUrl="@Context.Request.PathAndQuery()" 
                           class="btn btn-outline-primary">Edit</a>
                        <button type="submit" class="btn btn-outline-danger">Delete</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Economic/ECategories.cshtml
@model ECategoriesViewModel


    <h4 class="bg-primary p-2">Все типи Затрати</h4>

    <a asp-action="Create" asp-controller="ECategory" asp-route-returnUrl="@Context.Request.PathAndQuery()"
       class="btn btn-primary">Добавить</a>
    <table class="table table-striped table-sm table-bordered ">
        <thead>
            <tr>
                <th>Имя категория</th>
                <th>Определение</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <tr class="place"><td colspan="3" class="text-center">No Data</td></tr>
            @foreach (var c in Model.ECategories)
            {
                <tr>
                    <td>@c.Name</td>
                    <td>@c.Description</td>
                    <td>
                        <form method="post" asp-action="Delete" asp-controller="ECategory"
                              asp-route-returnUrl="@Context.Request.PathAndQuery()">
                            <input type="hidden" name="id" value="@c.Id" />
                            <a asp-action="Edit" asp-controller="ECategory"
                               asp-route-returnUrl="@Context.Request.PathAndQuery()"
                               asp-route-id="@c.Id" class="btn btn-outline-primary">Edit</a>
                            <button type="submit" class="btn btn-outline-danger">Delete</button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>

Views/Economic/Expenses.cshtml
@model PagedModel<Expense>

    <h4 class="bg-primary p-2">Затрати</h4>
    <a class="btn btn-primary" asp-action="Create" asp-controller="Expense"
       asp-route-returnUrl="@Context.Request.PathAndQuery()">Добавить</a>
    <table class="table table-striped table-sm table-bordered">
        <thead>
            <tr>
                <th>Имя владелеца</th>
                <th>Сумма</th>
                <th>Время</th>
                <th>Категория</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <tr class="place"><td colspan="5" class="text-center">No Data</td></tr>
            @foreach (var e in Model.Elements)
            {
                <tr>
                    <td>@e.AppUser.FirstName</td>
                    <td>@e.Amount</td>
                    <td>@e.DateExpense</td>
                    <td>@e.ECategory.Name</td>
                    <td>
                        <form method="post" asp-action="Delete" asp-controller="Expense"
                              asp-route-returnUrl="@Context.Request.PathAndQuery()">
                            <input type="hidden" name="id" value="@e.Id" />
                            <a class="btn btn-outline-primary" asp-route-id="@e.Id" asp-action="Edit"
                               asp-controller="Expense" asp-route-returnUrl="@Context.Request.PathAndQuery()">Редактировать</a>
                            <button class="btn btn-outline-danger" type="submit">Удалить</button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <td class="text-right">Количесиво</td><td>@Model.Elements.Count()</td>
                <td class="text-right">Сумма</td><td colspan="2">@Model.Elements.Sum(e=>e.Amount)</td>
            </tr>
        </tfoot>
    </table>


    <ul class="pagination">
        
        @foreach (DateTime date in Model.Months)
        {
            <li class="page-item">
                <a class="page-link @((date.Year==Model.Year && date.Month==Model.Month) ? "active" : "")"
                   asp-action="Expenses" asp-route-year="@date.Year"
                   asp-route-month="@date.Month">@(date.Year+"."+date.Month)</a>
            </li>
        }
        
    </ul>

Views/Economic/InCategories.cshtml
@model InCategoriesViewModel


    <h4 class="bg-primary p-2">Все типи доходи</h4>

    <a class="btn btn-primary" asp-action="Create" asp-controller="InCategory"
       asp-route-returnUrl="@Context.Request.PathAndQuery()">Добавить</a>
    <table class="table table-striped table-sm table-bordered">
        <thead>
            <tr>
                <th>Имя </th>
                <th>Определение</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <tr class="place"><td colspan="3" class="text-center">No Data</td></tr>
            @foreach (var c in Model.InCategories)
            {
                <tr>
                    <td>@c.Name</td>
                    <td>@c.Description</td>
                    <td>
                        <form method="post" asp-action="Delete" asp-controller="InCategory"
                              asp-route-returnUrl="@Context.Request.PathAndQuery()">
                            <input type="hidden" name="Id" value="@c.Id" />
                            <a class="btn btn-outline-primary" asp-action="Edit" asp-controller="inCategory"
                               asp-route-returnUrl="@Context.Request.PathAndQuery()" asp-route-id="@c.Id">Редактировать</a>
                            <button class="btn btn-outline-danger" type="submit">Удалить</button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>

Views/Economic/Incomes.cshtml
@model PagedModel<Income>

    <h4 class="bg-primary p-2">Доходи</h4>
    <a class="btn btn-primary" asp-action="Create" asp-controller="Income"
       asp-route-returnUrl="@Context.Request.PathAndQuery()">Добавить</a>
    <table class="table table-striped table-bordered table-sm">
        <thead>
            <tr>
                <th>Имя владелеца</th>
                <th>Имя категория</th>
                <th>Сумма</th>
                <th>Время</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <tr class="place"><td colspan="3" class="text-center">No Data</td></tr>
            @foreach (var i in Model.Elements)
            {
                <tr>
                    <td>@i.AppUser.FirstName</td>
                    <td>@i.InCategory.Name</td>
                    <td>@i.Amount</td>
                    <td>@i.DateSalary</td>
                    <td>
                        <form method="post" asp-action="Delete" asp-controller="Income"
                              asp-route-returnUrl="@Context.Request.PathAndQuery()">
                            <input name="id" type="hidden" value="@i.Id" />
                            <a class="btn btn-outline-primary" asp-action="Edit" asp-controller="Income"
                               asp-route-returnUrl="@Context.Request.PathAndQuery()" asp-route-id="@i.Id">Редактировать</a>
                            <button class="btn btn-outline-danger" type="submit">Удалить</button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <td class="text-right">Количество</td><td>@Model.Elements.Count()</td>
                <td class="text-right">Сумма</td><td colspan="2">@Model.Elements.Sum(e=>e.Amount)</td>
            </tr>
        </tfoot>
    </table>


    <ul class="pagination">
        
        @foreach (DateTime date in Model.Months)
        {
            <li class="page-item">
                <a class="page-link @((date.Year==Model.Year && date.Month==Model.Month) ? "active" : "")"
                   asp-action="Incomes" asp-route-year="@date.Year"
                   asp-route-month="@date.Month">@(date.Year+"."+date.Month)</a>
            </li>
        }
        
    </ul>

Views/Economic/WaitingTransactions.cshtml
@model PagedModel<WaitingTransaction>

    <h4 class="bg-primary p-2">Планирований транзакции</h4>
    <a class="btn btn-primary" asp-action="Create" asp-controller="WaitingTransaction"
       asp-route-returnUrl="@Context.Request.PathAndQuery()">Добавить</a>
    <table class="table table-striped table-sm table-bordered">
        <thead>
            <tr>
                <th>Имя владелеца</th>
                <th>Сумма</th>
                <th>Второй сторон транзакции</th>
                <th>Время соглашения</th>
                <th>Время выполнения</th>
                <th></th>
            </tr>
        </thead>
        <tr class="place"><td colspan="7" class="text-center">No Data</td></tr>
        @foreach (var w in Model.Elements)
        {
            <tr>
                <td>@w.AppUser.FirstName</td>
                <td>@w.Amount</td>
                <td>@w.PartnerDescription</td>
                <td>@w.StartDate</td>
                <td>@w.EndDate</td>
                <td>
                    <form method="post" asp-action="Delete" asp-controller="WaitingTransaction"
                          asp-route-returnUrl="@Context.Request.PathAndQuery()">
                        <input type="hidden" name="id" value="@w.Id" />
                        <a class="btn btn-outline-primary" asp-action="Edit" asp-controller="WaitingTransaction"
                           asp-route-returnUrl="@Context.Request.PathAndQuery()" asp-route-id="@w.Id">Редактировать</a>
                        <button class="btn btn-outline-danger" type="submit">Удалить</button>
                    </form>
                </td>
            </tr>
        }
    <tfoot>
        <tr>
            <td class="text-right">Ожидается</td>
            <td colspan="2">@Model.Elements.Where(w=>w.EndDate>DateTime.Now).Count()</td>
            <td class="text-right">Сумма</td><td colspan="2">@Model.Elements.Where(w => w.EndDate > DateTime.Now).Select(w=>w.isIncome?w.Amount:-1*w.Amount).Sum(w=>w)</td>
        </tr>
    </tfoot>
    </table>


    <ul class="pagination">
        
        @foreach (DateTime date in Model.Months)
        {
            <li class="page-item">
                <a class="page-link @((date.Year==Model.Year && date.Month==Model.Month) ? "active" : "")"
                   asp-action="WaitingTransactions" asp-route-year="@date.Year"
                   asp-route-month="@date.Month">@(date.Year+"."+date.Month)</a>
            </li>
        }
        
    </ul>